---
hero_image: images/tell-a-story.png
theme: green
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Tell a story
description: Create a webpage to tell a story, joke, or poem
original_url: https://codeclubprojects.org/en-GB/webdev/tell-a-story
interests: literature
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2018-12-01
steps:
- title: What you will make
- title: Editing your story
  completion:
  - engaged
- title: Telling your story
  completion:
  - internal
- title: Challenge
  challenge: true
- title: What can you do now?
  completion:
  - external
