---
hero_image: images/tell-a-story.png
theme: green
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Tell a story
description: कहानी, चुटकुला या कविता बताने के लिए एक वेबपेज बनाएं
original_url: https://codeclubprojects.org/en-GB/webdev/tell-a-story
interests: literature
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 0
last_tested: २०१८-१२-०१
steps:
  - 
    title: परिचय
  - 
    title: आपको किन चीजों की आवश्यकता होगी
  - 
    title: Decide on a story
  - 
    title: अपनी कहानी का संपादन
  - 
    title: 'चुनौती: कुछ बदलाव करें'
  - 
    title: अपनी कहानी बताना
  - 
    title: अपनी खुद की छवियां ढूंढना
  - 
    title: चित्र अपलोड करें
  - 
    title: 'चुनौती: चलते रहो!'
