---
hero_image: images/tell-a-story.png
theme: हरा
duration: 0
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Tell a story
description: कहानी, चुटकुला या कविता बताने के लिए एक वेबपेज बनाएं
original_url: https://codeclubprojects.org/en-GB/webdev/tell-a-story
interests: साहित्य
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 0
last_tested: २०१८-१२-०१
steps:
  - 
    title: परिचय
  - 
    title: आपको किन चीजों की आवश्यकता होगी
  - 
    title: Decide on a story
  - 
    title: Editing your story
  - 
    title: 'Challenge: make some changes'
  - 
    title: Telling your story
  - 
    title: Finding your own images
  - 
    title: Uploading images
  - 
    title: 'Challenge: keep going!'
