---
hero_image: images/tell-a-story.png
theme: green
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: 話をする
description: ストーリー、ジョーク、または詩を伝えるウェブページを作成する
original_url: https://codeclubprojects.org/en-GB/webdev/tell-a-story
interests: 文献
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2018-12-01
steps:
  - 
    title: 前書き
  - 
    title: あなたが必要とするもの
  - 
    title: 物語を決める
  - 
    title: あなたの話を編集する
  - 
    title: '課題：いくつかの変更を加える'
  - 
    title: あなたの話を伝える
  - 
    title: 自分の画像を見つける
  - 
    title: 画像のアップロード
  - 
    title: '挑戦：続ける！'
