---
hero_image: images/tell-a-story.png
theme: green
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: 物語を作ってみよう
description: 物語、ジョーク、または詩のウェブページを作成する
original_url: https://codeclubprojects.org/en-GB/webdev/tell-a-story
interests: literature
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2018-12-01
steps:
- title: はじめに
- title: 必要なもの
  completion: engaged
- title: 物語を決める
- title: 物語を編集する
- title: チャレンジ：いくつかの変更を加える
- title: あなたの物語を伝える
- title: 自分の画像を見つける
- title: 画像のアップロードをする
  completion: internal
- title: チャレンジ：続けよう！
