---
hero_image: images/tell-a-story.png
theme: green
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Conta uma história
description: Cria uma página de Internet para contar uma história, uma anedota ou
  um poema
original_url: https://codeclubprojects.org/en-GB/webdev/tell-a-story
interests: literature
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2018-12-01
steps:
- title: Introdução
- title: O que vais precisar
- title: Escolhe uma história
- title: Editar a tua história
  completion:
  - engaged
- title: 'Desafio: faz algumas mudanças'
- title: Contar a tua história
- title: Encontrar as tuas próprias imagens
- title: Carregar imagens
  completion:
  - internal