---
hero_image: images/tell-a-story.png
theme: green
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: 讲故事
description: 创建一个网页来讲述故事、笑话或诗歌
original_url: https://codeclubprojects.org/zh-CN/webdev/tell-a-story
interests: literature
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2018-12-01
steps:
- title: 介绍
- title: 你需要哪些准备
- title: 确定一个故事
- title: 编辑你的故事
  completion:
  - engaged
- title: 挑战：做一些更改
- title: 讲述你的故事
- title: 查找你自己的图片
- title: 上传图片
  completion:
  - internal
- title: 挑战：继续前进！
