---
hero_image: images/tell-a-story.png
theme: green
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Ispričaj priču
description: Napravi web stranicu za pričanje priče, vica ili pjesme
original_url: https://codeclubprojects.org/en-GB/webdev/tell-a-story
interests: književnost
technologies: html-css-javascript
site_areas: projekti
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2018-12-01
steps:
  - 
    title: Sretan rođendan
  - 
    title: Ono što će vam trebati
  - 
    title: Odlučite se za priču
  - 
    title: Uredite svoju priču
  - 
    title: 'Izazov: napravite neke promjene'
  - 
    title: Pričajte svoju priču
  - 
    title: Pronalaženje vlastitih slika
  - 
    title: Učitavanje slike
  - 
    title: 'Izazov: nastavite!'
