---
hero_image: images/tell-a-story.png
theme: green
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Ispričaj priču
description: U ovom projektu naučit ćeš napraviti web stranicu za pričanje priče, vica ili pjesme.
original_url: https://codeclubprojects.org/en-GB/webdev/tell-a-story
interests: literature
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2018-12-01
steps:
  - 
    title: Ispričaj priču
  - 
    title: What you will need
  - 
    title: Decide on a story
  - 
    title: Editing your story
  - 
    title: 'Challenge: make some changes'
  - 
    title: Telling your story
  - 
    title: Finding your own images
  - 
    title: Uploading images
  - 
    title: 'Challenge: keep going!'
