---
hero_image: images/tell-a-story.png
theme: green
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Cuenta una Historia
description: Crea una página web que narre una historia, broma o poema.
original_url: https://codeclubprojects.org/en-GB/webdev/tell-a-story
interests: literatura
technologies: html-css-javascript
site_areas: proyectos
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2018-12-01
steps:
  - 
    title: Introducción
  - 
    title: Decide que quieres contar
  - 
    title: Edita tu historia
  - 
    title: 'Desafío: Haz algunos cambios'
  - 
    title: 'Contando tu historia'
  - 
    title: 'Desafío: ¡Continuamos!'
  - 
    title: Encontrar tus propias imágenes
  - 
    title: Subir las imágenes
  - 
    title: 'Desafío: sigue adelante!'
