hero_image: images/tell-a-story.png
theme: green
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Adrodd stori
description: Cyfle i greu tudalen gwe i ddweud stori, jôc neu gerdd
original_url: https://codeclubprojects.org/en-GB/webdev/tell-a-story
interests: literature
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2018-12-01
steps: 
- title: Cyflwyniad
- title: Beth fyddi di ei angen
- title: Penderfynu ar stori
- title: Golygu dy stori 
- title: 'Her: gwneud rhai newidiadau'
- title: Dweud dy stori
- title: Dod o hyd i luniau
- title: Uwchlwytho lluniau
- title: "Her: parhau â'r stori!"
