---
hero_image: images/tell-a-story.png
theme: green
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Erzähle eine Geschichte
description: Erstelle eine Webseite, um eine Geschichte, einen Witz oder ein Gedicht
  zu erzählen
original_url: https://codeclubprojects.org/en-GB/webdev/tell-a-story
interests: literature
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2018-12-01
steps:
- title: Einleitung
- title: Was du brauchen wirst
  completion: engaged
- title: Entscheide dich für eine Geschichte
- title: Erstell deine Geschichte
- title: 'Aufgabe: mach ein paar Änderungen'
- title: Erzähl deine Geschichte
- title: Suche eigene Bilder
- title: Lade eigene Bilder hoch
  completion: internal
- title: 'Aufgabe: mach weiter!'
