---
hero_image: images/tell-a-story.png
theme: green
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Conte uma história
description: Neste projeto, você vai aprender como criar a sua própria página na web para contar uma história, anedota, piada ou poema.
original_url: https://codeclubprojects.org/en-GB/webdev/tell-a-story
interests: literature
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2018-12-01
steps:
  - 
    title: Conte uma história
  - 
    title: O que você vai precisar
  - 
    title: Escolha uma história
  - 
    title: Editing your story
  - 
    title: 'Desafio: faça algumas alterações'
  - 
    title: Contando sua história
  - 
    title: Encontrando suas próprias imagens
  - 
    title: Carregando imagens
  - 
    title: 'Desafio: continue!'
