---
hero_image: images / tell-a-story.png
theme: hijau
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, desain-1, pemrograman-0, phys-comp-0, manufacture-0, community-0
title: Bercerita
description: Buat halaman web untuk menceritakan kisah, lelucon, atau puisi
original_url: https://codeclubprojects.org/en-GB/webdev/tell-a-story
interests: literatur
technologies: html-css-javascript
site_areas: proyek
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2018-12-01
steps:
  - 
    title: pengantar
  - 
    title: Yang kamu butuhkan
  - 
    title: Tentukan sebuah cerita
  - 
    title: Edit ceritamu
  - 
    title: 'Tantangan: buat beberapa perubahan'
  - 
    title: Ceritakan ceritamu
  - 
    title: Temukan gambarmu sendiri
  - 
    title: Mengunggah gambar
  - 
    title: 'Tantangan: lanjutkan!'
