---
hero_image: images/tell-a-story.png
theme: green
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Explica una història
description: Crea una pàgina web per explicar una història, una broma o un poema
original_url: https://codeclubprojects.org/en-GB/webdev/tell-a-story
interests: literature
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2018-12-01
steps:
  - 
    title: Introducció
  - 
    title: Què necessitaràs
  - 
    title: Decideix sobre una història
  - 
    title: Edita la teva història
  - 
    title: 'Repte: fes alguns canvis'
  - 
    title: Explicant la teva història
  - 
    title: Trobant les teves imatges
  - 
    title: Carregant imatges
  - 
    title: 'Repte: continua endavant!'
