---
hero_image: images/tell-a-story.png
theme: green
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Vytvoř svůj příběh
description: Vytvoř webovou stránku, na které ukážeš svůj příběh, vtip nebo báseň
original_url: https://codeclubprojects.org/en-GB/webdev/tell-a-story
interests: literature
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2018-12-01
steps:
  - 
    title: Úvod
  - 
    title: Co budeš potřebovat
  - 
    title: Promysli svůj příběh
  - 
    title: Úprava tvého příběhu
  - 
    title: 'Výzva: pozměň pár věcí'
  - 
    title: Vyprávění tvého příběhu
  - 
    title: Nalezení tvých vlastních obrázků
  - 
    title: Nahrávání obrázků
  - 
    title: 'Výzva: pokračuj!'
