---
hero_image: images / tell-a-story.png
theme: zöld
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Elmondani egy történetet
description: Hozzon létre egy weboldalt egy történet, vicc vagy vers elmondására
original_url: https://codeclubprojects.org/en-GB/webdev/tell-a-story
interests: irodalom
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2018-12-01
steps:
  - 
    title: Bevezetés
  - 
    title: Mire lesz szükséged
  - 
    title: Döntsön egy történetről
  - 
    title: A történet szerkesztése
  - 
    title: 'Kihívás: végezzen néhány változtatást'
  - 
    title: Elmondja a történetedet
  - 
    title: Saját képek keresése
  - 
    title: Képek feltöltése
  - 
    title: 'Kihívás: folytassa!'
