---
hero_image: images/tell-a-story.png
theme: verde
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Cuenta una historia
description: Crea una página web que narre una historia, broma o poema
original_url: https://codeclubprojects.org/en-GB/webdev/tell-a-story
interests: literatura
technologies: html-css-javascript
site_areas: proyectos
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2018-12-01
steps:
  - 
    title: Introducción
  - 
    title: Lo que necesitarás
  - 
    title: Decídete por una historia
  - 
    title: Editando tu historia
  - 
    title: 'Desafío: haz algunos cambios'
  - 
    title: Cuenta tu historia
  - 
    title: Encontrando tus propias imágenes
  - 
    title: Subiendo imágenes
  - 
    title: 'Desafío: ¡sigue adelante!'
