---
hero_image: images/tell-a-story.png
theme: green
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: 이야기 설명하기
description: 이야기, 농담, 시 등을 설명하는 웹 페이지를 만드는 방법에 대해 배웁니다.
original_url: https://codeclubprojects.org/en-GB/webdev/tell-a-story
interests: literature
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2018-12-01
steps:
  - 
    title: 소개
  - 
    title: 준비물
  - 
    title: 이야기 결정하기
  - 
    title: 이야기 수정하기
  - 
    title: '과제: 몇 가지 변경하기'
  - 
    title: 이야기를 들려주세요
  - 
    title: 나만의 이미지 찾기
  - 
    title: 이미지 업로드하기
  - 
    title: '과제: 계속하세요!'
