---
hero_image: images/tell-a-story.png
theme: 녹색
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: 이야기 들려주기
description: 이야기, 농담, 시를 들려주는 웹 페이지 만드는 방법을 배워요.
original_url: https://codeclubprojects.org/en-GB/webdev/tell-a-story
interests: literature
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2018-12-01
steps:
- title: 들어가며
- title: 준비물
- title: 이야기 결정하기
- title: 이야기 수정하기
  completion:
  - engaged
- title: '과제: 몇 가지 변경하기'
- title: 이야기 들려주기
- title: 나만의 이미지 찾기
- title: 이미지 업로드하기
  completion:
  - internal
- title: '과제: 계속하세요!'
