---
hero_image: images/tell-a-story.png
theme: green
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Räägi lugu
description: Looge veebileht loo, nalja või luuletuse jutustamiseks
original_url: https://codeclubprojects.org/en-GB/webdev/tell-a-story
interests: literature
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2018-12-01
steps:
  - title: Sissejuhatus
  - title: Mida sul vaja on
  - title: Otsusta, mis lugu rääkida
  - title: Oma loo muutmine
  - title: 'Väljakutse: tee muudatusi'
  - title: Oma loo rääkimine
  - title: Sinu enda piltide leidmine
  - title: Piltide üleslaadimine
  - title: 'Väljakutse: jätka!'
