---
hero_image: pilte / tell-a-story.png
theme: roheline
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, disain-1, programmeerimine-0, phys-comp-0, production-0, community-0
title: Ütle lugu
description: Looge lehe, nalja või luuletuse saamiseks veebileht
original_url: https://codeclubprojects.org/en-GB/webdev/tell-a-story
interests: kirjandus
technologies: html-css-javascript
site_areas: projektid
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2018-12-01
steps:
  - 
    title: Sissejuhatus
  - 
    title: Mida peate
  - 
    title: Otsustage lugu
  - 
    title: Oma lugu redigeerides
  - 
    title: 'Väljakutse: tehke muudatusi'
  - 
    title: Räägib oma lugu
  - 
    title: Teie enda piltide leidmine
  - 
    title: Piltide üleslaadimine
  - 
    title: 'Väljakutse: jätkake!'
