---
hero_image: images/tell-a-story.png
theme: green
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Opowiadanie
description: Naucz się, jak stworzyć własną stronę internetową, aby opowiedzieć historyjkę, dowcip albo wiersz
original_url: https://codeclubprojects.org/en-GB/webdev/tell-a-story
interests: literature
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2018-12-01
steps:
  - 
    title: Wprowadzenie
  - 
    title: Czego będziesz potrzebować
  - 
    title: Wybierz historyjkę
  - 
    title: Redakcja Twojego opowiadania
    completion:
      - engaged
  - 
    title: 'Wyzwanie: Wprowadź pewne zmiany'
  - 
    title: Opowiedz swoją historię
  - 
    title: Poszukiwanie własnych obrazków
  - 
    title: Wgrywanie obrazków
    completion:
      - internal
  - 
    title: 'Wyzwanie: Nie zatrzymuj się!'
