---
hero_image: images/tell-a-story.png
theme: green
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Raconte une histoire
description: Créer une page Web pour raconter une histoire, une blague ou un poème
original_url: https://codeclubprojects.org/en-GB/webdev/tell-a-story
interests: literature
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2018-12-01
steps:
- title: Introduction
- title: Ce que tu auras besoin
- title: Choisis une histoire
- title: Modifie ton histoire
  completion:
  - engaged
- title: 'Défi: apporter quelques changements'
- title: Raconte ton histoire
- title: Trouver tes propres images
- title: Charger des images
  completion:
  - internal