---
hero_image: images/tell-a-story.png
theme: green
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Racconta una storia
description: Crea una pagina Web per raccontare una storia, una barzelletta o una
  poesia
original_url: https://codeclubprojects.org/en-GB/webdev/tell-a-story
interests: literature
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2018-12-01
steps:
- title: Introduzione
- title: Cosa ti servirà
- title: Scegli la storia
- title: Fai modifiche alla tua storia
  completion:
  - engaged
- title: 'Sfida: fai delle modifiche'
- title: Racconta la tua storia
- title: Cerca le tue immagini
- title: Carica immagini
  completion:
  - internal
- title: 'Sfida: continua!'
