---
hero_image: images / söyle-story.png
theme: yeşil
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, tasarım-1, programlama-0, phys-comp-0, üretim-0, topluluk-0
title: Bir hikaye anlatmak
description: Hikaye, şaka veya şiir anlatmak için bir web sayfası oluşturun
original_url: https://codeclubprojects.org/en-GB/webdev/tell-a-story
interests: Edebiyat
technologies: html CSS-JavaScript
site_areas: projeler
hardware: ''
software: html CSS-JavaScript
version: 4
last_tested: 2018/12/01
steps:
  - 
    title: Giriş
  - 
    title: Neye ihtiyacın olacak
  - 
    title: Bir hikayeye karar ver
  - 
    title: Hikayenizi düzenleme
  - 
    title: 'Zorluk: bazı değişiklikler yap'
  - 
    title: Hikayeni anlatmak
  - 
    title: Kendi resimlerinizi bulma
  - 
    title: Resimler yükleniyor
  - 
    title: 'Zorluk: devam et!'
