---
hero_image: images/tell-a-story.png
theme: green
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-1, programming-0, phys-comp-0, manufacture-0, community-0
title: Bir hikaye anlatın
description: Bir hikaye, şaka veya şiir anlatmak için bir web sayfası oluşturun
original_url: https://codeclubprojects.org/en-GB/webdev/tell-a-story
interests: literature
technologies: html-css-javascript
site_areas: projects
hardware: ''
software: html-css-javascript
version: 4
last_tested: 2018-12-01
steps:
  - 
    title: Giriş
  - 
    title: Nelere ihtiyacınız olacak
  - 
    title: Bir hikayeye karar verin
  - 
    title: Hikayenizi düzenleme
    completion:
      - engaged
  - 
    title: 'Meydan Okuma: bazı değişiklikler yapın'
  - 
    title: Hikayeni anlatmak
  - 
    title: Kendi resimlerinizi bulma
  - 
    title: Resimleri yükleme
    completion:
      - internal
  - 
    title: 'Meydan Okuma: devam et!'
